[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.0",
    "mcp[fastapi]>=0.1.0",
    "uvicorn>=0.30.0",
]
